### ISSUE TITLE
Tinkers Construct pickaxes not working on ore blocks

### ISSUE THREAD

**Issue by fangedhex** [The-Acronym-Coders/ContentTweaker#10]
**Mods used :** 
forge-1.11.2-13.20.0.2311
Mantle-1.11.2-1.2.0.26
TConstruct-1.11.2-2.7.0.26
CraftTweaker-1.11.2-3.0.25.103
base-1.11.2-2.0.0-Snapshot.3
ContentTweaker-1.11.2-3.0.0-Snapshot.5

**What SHOULD happen :** 
The pickaxe should start to break the block.

**What ACTUALLY happen :**
The pickaxe does nothing to the block

**Comment by SkySom** [comment]
I believe this should be fixed now.
