### ISSUE TITLE
Vanilla textures not changing

### ISSUE THREAD

**Issue by ghost** [The-Acronym-Coders/ContentTweaker#100]
I am uncertain this is a bug since my memory might be faulty.
But ever since the april fool's texture joke from Mojang, any custom textures in /<instance>/resources/minecraft/textures/...  no longer work (this might also be a B.A.S.E. bug if at all?)
Assets form other mods (e.g. /<instance>/resources/ceramics/textures/... and ofcourse /<instance>/resources/contenttweaker/textures/...) DO work. So it is just the MC ones.
Again, perhaps I am mistaken, but I seem to remember it worked fine before april 1st (or thereabouts).

**Comment by SkySom** [comment]
Yeah if this is still a thing, not much I can do. I specifically use the MC resource system.
