### ISSUE TITLE
Food Item alwaysEditable don't work

### ISSUE THREAD

**Issue by Gorden121** [The-Acronym-Coders/ContentTweaker#102]
I tried to create a Food Item like for example a golden apple with the alwaysEditable Property.

But when I start the game I can still only eat the item if the food bar lacks at least half a hunger club.

**Comment by SkySom** [comment]
Fixed by: https://github.com/The-Acronym-Coders/ContentTweaker/commit/c0b99237088e74950a96dbcc77d21580ee7a2f9d
