### ISSUE TITLE
Problems with localization

### ISSUE THREAD

**Issue by slava110** [The-Acronym-Coders/ContentTweaker#108]
After client started with this mod, in all localization files (resources folder) russian letter "И" replaced to unkown symbol.
item.coin_emerald.name=Изумрудная монета
replaced to
![image](https://user-images.githubusercontent.com/26705162/40067427-c6f6bce8-586e-11e8-8433-db11a58c49dc.png)
And every letter "И" replaced to unkown symbol.

**Comment by SkySom** [comment]
I need scripts and pre and post run Lang files

**Comment by slava110** [comment]
Empty scripts folder
[Lang files before and after start.zip](https://github.com/The-Acronym-Coders/ContentTweaker/files/2006110/Lang.files.before.and.after.start.zip)

**Comment by Yesterday17** [comment]
I also encounterred this problem. Every time I launch the game, the lang file is turned to this(showed in diff):
![default](https://user-images.githubusercontent.com/8667822/40571469-fabcefd8-60cb-11e8-8b6d-b916b28faed8.PNG)

All the scripts are available on [Github](https://github.com/Yesterday17/FluidVoid).
Post run lang files [here](https://pastebin.com/d4mTr8sn).

**Comment by SkySom** [comment]
Fixed in next BASE release
