### ISSUE TITLE
[Suggestion] Enchantment glow effect

### ISSUE THREAD

**Issue by ghost** [The-Acronym-Coders/ContentTweaker#111]
This would basically add an extra arguments to allow adding a glow effect to an item you make, or make the item variant of a block glow as well.

Item version:
`"var name".itemGlowing = true/false;`

Example:
```
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Item;

var zsItem = VanillaFactory.createItem("zs_item");
zsItem.maxStackSize = 1;
zsItem.rarity = "rare";
zsItem.beaconPayment = true;
zsItem.itemGlowing = true;
zsItem.register();
```

**Comment by SkySom** [comment]
Read the docs. Glowing is already a property

**Comment by SextupleTap** [comment]
How is this done then...

**Comment by ghost** [comment]
What is the exact method for it then.

**Comment by justinrusso** [comment]
`glowing`
