### ISSUE TITLE
Parsing error when trying to create Tinkers' Construct materials.

### ISSUE THREAD

**Issue by tacticalretard** [The-Acronym-Coders/ContentTweaker#114]
I am trying to create materials for Tinkers' Construct tools, and I keep running into parsing errors that keep the script from loading, stating "9 -- ) expected". I'm guessing I did something wrong, so I wanted to ask if I could get help, if I need to post my scripts, and if so, where to do so.

**Comment by SkySom** [comment]
Usually our discord (Listed on the curse page) is the best place to check things, but really it sounds like you just need to double check you've got the right symbols and such.
