### ISSUE TITLE
Materials system blocks turn to bedrock texture after deletion of a block in script

### ISSUE THREAD

**Issue by ThatGravyBoat** [The-Acronym-Coders/ContentTweaker#115]
After i deleted a material system block from my script and restarted my game all my blocks in 
inventory block textures are bedrock but when placed its the right texture.

![2018-06-25_06 38 52](https://user-images.githubusercontent.com/26934102/41841453-e03a3e2a-7842-11e8-827d-cd84d7960c6c.png)

**Comment by SkySom** [comment]
Did you have any times where you had broken scripts between the two loads?

**Comment by ThatGravyBoat** [comment]
If you count that i had an error that i registered black_iron_bolt twice then yes but /ct syntax doesn't show any errors so i would say i didn't have a broken script between the two loads.

The error i got about the black_iron_bolt registry problem below. 

![2018-06-25_13 00 55](https://user-images.githubusercontent.com/26934102/41859929-e45b831c-7877-11e8-945f-3bd142e9baca.png)

**Comment by ThatGravyBoat** [comment]
so testing this in another pack with just contenttweaker, base, crafttweaker, and jei it does the same thing but this time it gave one of the block a ore texture even tho it was a block but again when placed it was the right texture but the item texture was not right.

**Comment by ThatGravyBoat** [comment]
I dont know if this helps but it fixed the problem after i broke a script and reloaded the game after fixing the script

**Comment by belathus** [comment]
I was having a similar issue when I removed a ton of materials that I had registered. Looks like making more blocks to replace the ones that got removed helps. Also, even though they look like bedrock in your inventory, they have the correct texture when placed in the world.

**Comment by SkySom** [comment]
Yeah It's something I continue to look into. It's a rather odd issue. I think it may have to do with subblock saving.
