### ISSUE TITLE
Gravity Affected Blocks

### ISSUE THREAD

**Issue by SkySom** [The-Acronym-Coders/ContentTweaker#12]
Allow for blocks to act like Sand

**Comment by Divineaspect** [comment]
I was thinking of making a sandstorm. looks like sand block, when the weather is storming it transforms into a floating liquid block which flows upwards, and spreads out at it's max height. the flowing block stays what it is until the weather changes back, and it transforms into falling sand.

**Comment by justinrusso** [comment]
Was looking at this, but I got a bit stuck. You override `updateTick` to add custom triggers, but that is when it normally will check if it should fall. `checkFallable` cant be called because its a private method

**Comment by SkySom** [comment]
Added by #154
