### ISSUE TITLE
Contenttweaker custom made samples will not load with geolosys

### ISSUE THREAD

**Issue by Trinsdar** [The-Acronym-Coders/ContentTweaker#123]
## Versions:

- Minecraft Forge:14.23.4.2739
- Geolosys: 2.0.0
- Contenttweaker 4.6.0

## What happens:
Geolosys keeps saying that the custom samples I made using contenttweaker do not exist, yet they do exist.

## What should happen:
Geolosys should recognize it as a valid block.

## Logs (if necessary):
https://paste.dimdev.org/gasimuqusi.md

## Additional Comments:
this is the exact line: https://paste.dimdev.org/cagopibuba.css
Is it possible that caonttweaker is not loading scripts early enough?

https://github.com/oitsjustjose/Geolosys/issues/146

**Comment by SkySom** [comment]
I need your script file as well as all files in the saved directory of the acronym config folder

**Comment by Trinsdar** [comment]
[contenttweaker_scripts.zip](https://github.com/The-Acronym-Coders/ContentTweaker/files/2217042/contenttweaker_scripts.zip)
[saved_files.zip](https://github.com/The-Acronym-Coders/ContentTweaker/files/2217043/saved_files.zip)
