### ISSUE TITLE
Question: Variant for ore with Metadata

### ISSUE THREAD

**Issue by IcedReaper** [The-Acronym-Coders/ContentTweaker#128]
Hi,

I'm trying to implement some new ores and would like to use a block with metadata as the variant.
I tried the following statements. Sadly I got the "block not found" texture in all three cases:

> ore.addDataValue("variants", "extraplanets:eris:2");
> ore.addDataValue("variants", "extraplanets:eris@2");
> ore.addDataValue("variants", "extraplanets:eris/2");

Here is the complete script right now with the last two for testing: https://pastebin.com/BqnAqC8i

What is the correct way to create a variant with a block with metadata?

Thanks in advance.
IcedReaper

**Comment by SkySom** [comment]
That's because it's not a block, it's just the texture location that goes in variants

**Comment by IcedReaper** [comment]
Thanks for the info.
