### ISSUE TITLE
[Request] Adding possibility to made a block Wither Proof

### ISSUE THREAD

**Issue by Fireztonez** [The-Acronym-Coders/ContentTweaker#129]
Hello, I wonder if you can add Field to set a block Wither Proof in Vanilla Factory... I Want to make Somes Blocks for made Wither Farm in my modpack, but we have no Wither Proof blocks for now and I don<t want to add a mod just for that ;).

Thank's
Fireztonez

**Comment by onyxromero** [comment]
All ya have to do is change the hardness...

**Comment by xkforce** [comment]
That isn't true.

**Comment by SkySom** [comment]
Added by #156
