### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by SkySom** [The-Acronym-Coders/ContentTweaker#13]
Allow Items to act as food.

**Comment by KAfable** [comment]
Would also like to see this implemented, some additional/optional thoughts:
- Ability to add in potion effects by potion ID (modded as well as vanilla if possible), duration on those potion effects, as well as magnitude
- Not sure if this should be on Nutrition's side or CoT's side, but ability to set Nutrition levels as well
- Duration on eating time in ticks

**Comment by SkySom** [comment]
There's a potion bracket handler in craft tweaker. So that's handled as well as applying potion effects.

**Comment by SkySom** [comment]
Nutrition stuff is all on their side.

**Comment by SkySom** [comment]
Should work in 4.4.0
