### ISSUE TITLE
[Request] Add equivalent to itemColorSupplier for Vanilla Factory Blocks

### ISSUE THREAD

**Issue by Fireztonez** [The-Acronym-Coders/ContentTweaker#130]
As I spoke on the Discord, there is no way to color the blocks added by Vanilla Factory, as it is possible to do for liquids or items (_itemColorSupplier_). I think it would be a good thing to add this possibility at the level of Vanilla Factory. For now, the only possibility is to apply manually the color to the texture.

Fireztonez

**Comment by SkySom** [comment]
Added by #152
