### ISSUE TITLE
[Question]can u add potion effects 

### ISSUE THREAD

**Issue by avidgamer5918** [The-Acronym-Coders/ContentTweaker#132]
I was wondering if there is a way u can add potion effects to a custom item?

**Comment by nihiltres** [comment]
(Not a ContentTweaker dev.) You can make use of at least vanilla potion effects by using the `performEffect(IEntity)` method from `IPotionEffect`. You get an `IPotionEffect` from an `IPotion`, which in turn you get from the potion bracket handler. See [IPotionEffect](https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Potions/IPotionEffect/) in the documentation.

**Comment by avidgamer5918** [comment]
Can u show how that script would be written I cant figure out how one would write it.
