### ISSUE TITLE
[Request] Group Item IDs by Material instead of Parts per Item (or add the option to)

### ISSUE THREAD

**Issue by PyroBurnem** [The-Acronym-Coders/ContentTweaker#135]
As in, there should be a way to group the generated items into their own ID where everything within that ID is the same material, but this also enables different amounts of metadata per item ID, for something like if there were more platinum parts than cobalt parts for example.

~~Also just for cosmetics since an ID per material seems more fitting than filling up metadata for IDs with both platinum and cobalt parts.~~

**Comment by SkySom** [comment]
But why. It literally doesn't matter. Besides, the preferred way is to go into the Material configs and switch mad Suze to one so that the system doesn't even try to combine things into single items at all.

**Comment by PyroBurnem** [comment]
Hmm, yea I see the reasoning. I guess I just wanted stuff to look good in JEI. ¯\\\_(ツ)_/¯

**Comment by kindlich** [comment]
Well, you could try to remove all the items from JEI and add them back in in the order that you want them to appear :stuck_out_tongue:
