### ISSUE TITLE
CreativeTab 'works' but background is missing grid texture

### ISSUE THREAD

**Issue by plackyfantacky** [The-Acronym-Coders/ContentTweaker#136]
This is the code I'm using and it mostly works.

`#loader contenttweaker

import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Block;
import mods.contenttweaker.Item;
import mods.contenttweaker.IItemRightClick;
import mods.contenttweaker.MaterialSystem;
import mods.contenttweaker.Material;
import mods.contenttweaker.ResourceLocation;
import mods.contenttweaker.CreativeTab;

var scrap_tab = VanillaFactory.createCreativeTab("scrapyard", <item:minecraft:fireworks>);
scrap_tab.register();

var ruby = VanillaFactory.createItem("scrap_ruby");
ruby.rarity = "rare";
ruby.creativeTab = scrap_tab;

ruby.register();`

![2018-09-11_15 14 07](https://user-images.githubusercontent.com/2724084/45344089-64e21600-b5d5-11e8-9dc5-d7dcc0dd0f03.png)
![2018-09-11_15 14 12](https://user-images.githubusercontent.com/2724084/45344120-71ff0500-b5d5-11e8-9812-970f9c7d654c.png)

[crafttweaker.log](https://github.com/The-Acronym-Coders/ContentTweaker/files/2369745/crafttweaker.log)

- Forge 14.23.4.2760
- base-1.12.2-3.10.0.jar
- blockdrops-1.12.2-1.4.0.jar
- ContentTweaker-1.12.2-4.8.0.jar
- CraftTweaker2-1.12-4.1.9.jar
- jei_1.12.2-4.12.0.216.jar
- modtweaker-4.0.13.jar
- MTLib-3.0.5.jar

Hope its something I've just missed.

**Comment by plackyfantacky** [comment]
Other tabs are ok
![2018-09-11_15 22 40](https://user-images.githubusercontent.com/2724084/45344566-9f987e00-b5d6-11e8-8c83-e538873479a1.png)

**Comment by SkySom** [comment]
Fixed by #143
