### ISSUE TITLE
DS Crash: Redstone related?

### ISSUE THREAD

**Issue by mike347** [The-Acronym-Coders/ContentTweaker#139]
https://pastebin.com/ZmwUmbNH

Server just crashed with the above. The setup that caused is:

Timer->redstone dust->AA atomic reconstructor->redstone dust->redstone repeater (4 ticks)->redstone repeater (4 ticks)->redstone dust->piston.

This is on the Undiscovered modpack.

**Comment by mike347** [comment]
And another one. After MCediting out the redstone, replacing everything. The moment redstone is placed down, server crashes.
https://pastebin.com/1dNwXQLp

**Comment by mike347** [comment]
Update: I believe this is related to trying to push (with a piston) a contentTweaker added block that is tool level 3 (obsidian level), at the same time it was being changed {(Via AA atomic reconstructor with mining lens) via redstone pulse.

This is the block in question:

`var osmaticSteelOre = VanillaFactory.createBlock("osmaticsteelore", <blockmaterial:rock>);
osmaticSteelOre.setToolLevel(3);
osmaticSteelOre.setToolClass("pickaxe");
osmaticSteelOre.register();`

**Comment by SkySom** [comment]
It's the Piston. I see the issue. If there's no mobility flag set on the representation it breaks.

**Comment by mike347** [comment]
And the infinite loop is caused by the repeaters. I'm not sure if this is true everywhere, but in this modpack, if you place a piston down and power it against a block it can't move (e.g. obsidian), then remove the redstone, the redstone is still active, which feeds back into the repeater(s) and cause the loop, which crashes.
