### ISSUE TITLE
Suggestion: link to contenttweaker section in crafttweaker wiki on this wiki page

### ISSUE THREAD

**Issue by mindlessmrwaesome** [The-Acronym-Coders/ContentTweaker#140]
So I was struggling to figure out why my script wasn't working by looking at the examples put on this github, so I decided to join your guys' discord to seek help. I was eventually guided to the _actual_ contenttweaker wiki where I learned much more about contenttweaker than on this wiki and actually got my script to work. Maybe it would be worthwhile to post a link to the actual contenttweaker wiki on the home page of this github wiki? It would really help us noobs out XD

**Comment by SkySom** [comment]
The ContentTweaker wiki is on the CraftTweaker wiki? Just under the mods section
