### ISSUE TITLE
[Request] Functions needed to add vanilla style soups i.e. transform to another item on use

### ISSUE THREAD

**Issue by xkforce** [The-Acronym-Coders/ContentTweaker#146]
In vanilla, when soups are eaten, they provide saturation + hunger points and then convert to empty bowls.  Currently food items can only be consumed, they can't "transform" into any other item like that.

**Comment by SkySom** [comment]
Dup of #109 WHICH IS LITERALLY BY YOU

**Comment by xkforce** [comment]
my bad :/
