### ISSUE TITLE
[Feature Request] Bauble Creation

### ISSUE THREAD

**Issue by duhadventure** [The-Acronym-Coders/ContentTweaker#149]
Feature:
The ability to create baubles that can be defined as:
- Ring
- Amulet
- Belt
- Head
- Body
- Charm
As well as the ability to trigger a command or a potion effect that turns off when removed. Rendering the baubles on body doesn't need to be added just the ability to make them.

**Comment by Dimentive** [comment]
I would like this too.

**Comment by Dimentive** [comment]
I really want this as well.

**Comment by katubug** [comment]
I arrived here because I was googling for this exact feature. I'm not sure if 1.12 is still being given new features, but I would be very interested in this ability as well. :)

**Comment by SkySom** [comment]
While 1.12 is indeed feature complete, the reason for this never being completed, was a realization after it's creation, that it shouldn't be done in contenttweaker.
