### ISSUE TITLE
IBlockDropHandler not working

### ISSUE THREAD

**Issue by thanasishadow** [The-Acronym-Coders/ContentTweaker#151]
`import mods.contenttweaker.DropHandler;`
gives me the following error.
[![javaw-2018-12-02-16-09-07.jpg](https://i.postimg.cc/m28ChwnS/javaw-2018-12-02-16-09-07.jpg)](https://postimg.cc/fJSJrxD3)

**Comment by thanasishadow** [comment]
Update: works if you don't import the drop handler.

**Comment by SkySom** [comment]
Fixed by #153
