### ISSUE TITLE
[Suggestion] Ability to set opacity of fluid colors

### ISSUE THREAD

**Issue by xkforce** [The-Acronym-Coders/ContentTweaker#159]
Currently AFAIK you can either color a liquid or remove coloration entirely but there isn't really a way to set how transparent the liquid is.  i.e somewhere between fully transparent and deeply colored to the point of being opaque.

**Comment by SkySom** [comment]
Have you tried passing alpha in the Color creation?

**Comment by xkforce** [comment]
Not yet, there's no mention of it in the fluid creation or color sections of the wiki and I haven't found the section that talks about alpha as a parameter so as soon as I figure out how to do that I will.

**Comment by SkySom** [comment]
https://css-tricks.com/8-digit-hex-codes/

**Comment by xkforce** [comment]
So I assume that that's what setcolor was for since it accepts ints instead of hex.
