### ISSUE TITLE
Simple Examples - missing info

### ISSUE THREAD

**Issue by gdarai** [The-Acronym-Coders/ContentTweaker#16]
Hi,
I have simmilar request as some other poor fellow, 26 days ago, BUT it is not the same issue, because what I would need is the most basic stuff examples:
So here are my quesions - requirenments:

- Where to put the script?
- What are those script commands on mineTweaker3 page? Do they work? Where and how?
(Example what is there: mods.content.Block.registerBlock("Content", "content_block", "rock", "content_block", "misc", 1, [<minecraft:dirt>, <minecraft:diamond>], false, 0.5f, 0.8f, 2);)
- How to set up Item Name (to not have only displayed package.itemName)
- How to set up Item Image to use existing item from within the game?
- How to set up Item Image to use some custom resources (and where to put them)?
- How to set up block's Model and texture? Where to pt it, what formats are supported?
- How to refference the created items in other mincraftTweaker scripts?
- What all parameters are implemented for: Items, Blocks, Fluids, TC stuff? How can I find such a list if it exists?

Thanks for the good work. I hope, this mod can fix all my issues, once I will be able to push it to actually create something.

**Comment by SkySom** [comment]
To answer some of the questions (Ill answer more as I have time)

Where to put scripts: <config folder>/ACROMYM/ContentTweaker/scripts

Where to find supported parameters: look at the wiki tab here on github. You'll find the list of parameters as well as a small description of each.

Textures and formats: ContentTweaker uses the vanilla model system, so anything that it supports, we do. For the most part for basic models, you need only put textures in right place in the textures folder I'm the resource folder in the Content tweaker config folder.

**Comment by SkySom** [comment]
Also to note, the information on the Minetweaker wiki is for the 1.7.10 version, not the 1.10+ version.

**Comment by SkySom** [comment]
Mostly handed through http://crafttweaker.readthedocs.io/en/latest/#Mods/ContentTweaker/WalkThrough/ and more will be added as documentation progress continues
