### ISSUE TITLE
system: TileEntity is already defined in that package

### ISSUE THREAD

**Issue by xkforce** [The-Acronym-Coders/ContentTweaker#160]
[PREINITIALIZATION][CLIENT][ERROR] system: TileEntity is already defined in that package

ContentTweaker-1.12.2-4.9.0
base-1.12.2-3.11.0
CraftTweaker2-1.12-4.1.13

**Comment by Slowwloriss** [comment]
I have the same text in chat when login in the world.  

>  [CHAT] ERROR: system: TileEntity is already defined in that package

**Comment by kindlich** [comment]
Note for Sky/devs:

api/CTObjects/TE/IMCTE and MCTE both have the signature of "... .TileEntity", hence the error.

Also, some types in Modules/Vanilla/TileEntity aren't properly registered, check that all the classes have the appropriate `@ZenClass` and `@ZenRegister` annotations ^^

**Comment by xkforce** [comment]
Well done.
