### ISSUE TITLE
Trying to diagnose an unrelated crash, ran into this

### ISSUE THREAD

**Issue by Sunconure11** [The-Acronym-Coders/ContentTweaker#161]
https://paste.dimdev.org/esisanokoy.mccrash

**Comment by SkySom** [comment]
Submitting an issue multiple times does not make it more likely to be fixed. Duplicate of #138 and #150

**Comment by Sunconure11** [comment]
Wait, WTF? I submitted this fairly late, didn't realize it was the same error as before. And yet I haven't touched my scripts.

**Comment by SkySom** [comment]
There's something up with your lang file such that it isn't loading right. No idea yet.
