### ISSUE TITLE
Error when trying to add drops with tags

### ISSUE THREAD

**Issue by Prunoideae** [The-Acronym-Coders/ContentTweaker#164]
Code is simple:
![image](https://user-images.githubusercontent.com/24620047/50720011-1f93a800-10e0-11e9-81dd-d3916132f765.png)
I'm trying to create a ore that drops item with certain tag, but an error message is sent every time I break the ore:
![image](https://user-images.githubusercontent.com/24620047/50720028-62ee1680-10e0-11e9-9fe3-d0d0f90a6552.png)
The game doesn't crash and the tag was set correctly:
![image](https://user-images.githubusercontent.com/24620047/50720042-8a44e380-10e0-11e9-9975-203c4b15f8dd.png)
But that error message is really annoying.

**Comment by kindlich** [comment]
This should already be fixed in the latest release.
The changes fixing this were committed on Oct 27, 2018

**Comment by Prunoideae** [comment]
Oh, that's a silly mistake, I'm running on 4.8.0 and the problem was solved after update it to 4.9.1. Thank you.
