### ISSUE TITLE
Unable to operate with ICTItemList

### ISSUE THREAD

**Issue by EngineerXL** [The-Acronym-Coders/ContentTweaker#167]
I wanted to add an advanced drop from block, but got this error:
![image](https://user-images.githubusercontent.com/37447286/50776639-97153300-12aa-11e9-93dd-792ede6ed4a2.png)
Used script: https://pastebin.com/ppD6dqUg
CT log: https://pastebin.com/fgh4YHLi
I also tried WiKi example, but it did not work

**Comment by SkySom** [comment]
You can't use CraftTweaker's Item Bracket in ContentTweaker scripts you need to do <item:minecraft:coal>

**Comment by EngineerXL** [comment]
This does not work too. Now this 
![image](https://user-images.githubusercontent.com/37447286/50777685-4d7a1780-12ad-11e9-8e48-77832a464616.png)
Also, why Wiki says that I should use IItemStack? https://crafttweaker.readthedocs.io/en/latest/#Mods/ContentTweaker/Vanilla/Advanced_Functionality/Functions/IBlockDropHandler/

**Comment by EngineerXL** [comment]
Script: https://pastebin.com/KKm0wBWw

**Comment by SkySom** [comment]
Docs are wrong, your script is still wrong. Issues aren't for script support. Please join us in discord.

**Comment by EngineerXL** [comment]
Sorry, where can I find Discord link?
