### ISSUE TITLE
Unable to use Part metal_leaves

### ISSUE THREAD

**Issue by NielsPilgaard** [The-Acronym-Coders/ContentTweaker#170]
Registering part `metal_leaves` for a Material results in an IndexOutOfBounds exception.

[Snippet of crafttweaker.log](https://gist.github.com/NillerMedDild/9922097e2717c0fcec0fbd94aa875bdd)
[Full crafttweaker.log](https://gist.github.com/NillerMedDild/318976a0e81b1ebc8c785ecbc6a0aaee)

Scripts used, the relevant lines are at the bottom:
[materials](https://gist.github.com/NillerMedDild/2f6845ae01845508168159bdd093c5d8)
[parts](https://gist.github.com/NillerMedDild/f26986b8d3181781219829328e208ce2)

**Comment by SkySom** [comment]
Metal Leaves aren't a valid part.

**Comment by NielsPilgaard** [comment]
Damn. What is the purpose of the metal_leaves texture then?

**Comment by Lanse505** [comment]
It's a not yet implemented part type.
There is no ETA on it being implemented.

**Comment by NielsPilgaard** [comment]
Alright, thanks for the quick answer.
