### ISSUE TITLE
Scroll bar missing when creating a custom creative tab

### ISSUE THREAD

**Issue by Zergmazter** [The-Acronym-Coders/ContentTweaker#171]
#loader contenttweaker

import mods.contenttweaker.CreativeTab;

var metalCrafts = VanillaFactory.createCreativeTab("metal_crafts", <item:contenttweaker:hot_tin_block>);
metalCrafts.register();

This code created a creativeTab, but it's missing a scroll button to scroll through items.

**Comment by SkySom** [comment]
Fixed
