### ISSUE TITLE
/ct creativetabs not showing all tabs

### ISSUE THREAD

**Issue by Renari** [The-Acronym-Coders/ContentTweaker#173]
When using the above to get the creative tab ids there are many tabs that are missing from the output.

- NuclearCraft
- Recurrent Complex
- TeaStory
- EnderIO
- Netherending Ores
- Pixelmon
- Spartan Shields
- Extra Alchemy
- Extra Cells 2
- Enderman Evolution

**Comment by SkySom** [comment]
Means they don't exist when ContentTweaker runs. Generally when creating items you should either put them in MC tabs or in a custom ContentTweaker tab
