### ISSUE TITLE
Diagonal Texture Bug on High Resolution Blocks

### ISSUE THREAD

**Issue by JakeOTwitch** [The-Acronym-Coders/ContentTweaker#175]
I'm attempting to add a custom block to the game that has a high resolution (300x300). The texture loads and looks good on the item until you back away from it. At that point the image warps diagonally. Is this strictly due to the resolution or is there still something I can do to keep the resolution while also getting rid of the warping? Thanks for your time!
![2019-04-22_23 27 38](https://user-images.githubusercontent.com/30060800/56551395-4f16d500-6556-11e9-807f-304547fda4fd.png)
![2019-04-22_23 27 42](https://user-images.githubusercontent.com/30060800/56551400-50e09880-6556-11e9-9bf3-64b10f72ba5b.png)

**Comment by SkySom** [comment]
Textures need to be a multiple of 2.
