### ISSUE TITLE
Adjacent blocks are transparent with custom glass block

### ISSUE THREAD

**Issue by Dimentive** [The-Acronym-Coders/ContentTweaker#177]
I made a custom translucent glass-like block in ContentTweaker, and it works fine except for one thing: Whenever there’s a block adjacent to it, regardless of which side, I can see through the world on that side.

![2019-05-08_13 43 01](https://user-images.githubusercontent.com/34230933/57372902-3a158500-7197-11e9-97fd-0421286d1f24.png)

This issue seems similar to #25, but I’m not using a custom JSON script; I haven’t altered it. Also, it was, apparently, fixed in a dev build back in 2017.

#### Script

    #loader contenttweaker
    import mods.contenttweaker.VanillaFactory;
    import mods.contenttweaker.Block;

    var blueGlass = VanillaFactory.createBlock("blueglass", <blockmaterial:glass>);
    blueGlass.setBlockHardness(0.3);
    blueGlass.setBlockResistance(1.5);
    blueGlass.setBlockLayer("TRANSLUCENT");
    blueGlass.setLightOpacity(0);
    blueGlass.setTranslucent(true);
    blueGlass.setBlockSoundType(<soundtype:glass>);
    blueGlass.register();

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2816
* **CraftTweaker:** 4.1.17 (latest)
* **ContentTweaker:** 4.9.1 (latest)

**Comment by SkySom** [comment]
YOu didn't set Full Block to false

**Comment by Dimentive** [comment]
Ah, you’re right. Thanks.
