### ISSUE TITLE
file encoding always use ANSL

### ISSUE THREAD

**Issue by yaohuomhuom** [The-Acronym-Coders/ContentTweaker#178]
![图片](https://user-images.githubusercontent.com/31821405/60442446-9e127200-9c4b-11e9-9061-d87d4cbe145a.png)
![图片](https://user-images.githubusercontent.com/31821405/60442465-a66aad00-9c4b-11e9-9fa3-6749b7fde8ed.png)
when i edit the lang file  and use the chinese ，it always become ANSL codeing after i open the game.
i also try unicode,but it just read as English。
![图片](https://user-images.githubusercontent.com/31821405/60442791-66f09080-9c4c-11e9-8a40-dc19c5a15ba2.png)
![图片](https://user-images.githubusercontent.com/31821405/60442807-6e179e80-9c4c-11e9-9591-b2b0b53265a1.png)

**Comment by yaohuomhuom** [comment]
it is the SevTech: Ages mods，but i just use it some mod to test
this is my mod list
![图片](https://user-images.githubusercontent.com/31821405/60443797-8e485d00-9c4e-11e9-8126-77cbb629979c.png)

**Comment by xinyuan-liu** [comment]
Already fixed in https://github.com/The-Acronym-Coders/BASE/commit/7187e9b1ab293018d2daefc76fe9f360da6e958a.
