### ISSUE TITLE
Overlays does not work properly

### ISSUE THREAD

**Issue by Krakenrek** [The-Acronym-Coders/ContentTweaker#186]
![2019-09-12_23 00 22](https://user-images.githubusercontent.com/43118568/64817011-88a5b680-d5b1-11e9-9f65-1bacb22969ae.png)
https://gist.github.com/KRAKENREK/896e1f44ef34197504be1418b50b7081
![itstone_ore](https://user-images.githubusercontent.com/43118568/64817405-7710de80-d5b2-11e9-9b5f-628ad9ec1c30.png)
![itstone_ore_Overlay](https://user-images.githubusercontent.com/43118568/64817407-7710de80-d5b2-11e9-86e6-7895883654ed.png)

**Comment by SkySom** [comment]
Pretty sure it does considering, the basic parts already use it. Also most the things you're creating parts of, already exist, or are doable without creating additional parttypes.

**Comment by SkySom** [comment]
Correction. Overlay isn't for Blocks, so that's why it doesn't work. Overlay is for Items. Ores should use Ores, though I reiterate that you're building parts that already exist.
