### ISSUE TITLE
Error when assigning materials to newly created Parts

### ISSUE THREAD

**Issue by Prunoideae** [The-Acronym-Coders/ContentTweaker#188]
Installed Mods:
ContentTweaker 1.12.2 - 4.9.1
B.A.S.E 1.12.2 - 3.13.0
CraftTweaker - 1.12.2 - 4.1.19

Description of Issue:
An error was thrown when I'm trying to create my own set of parts and materials.
As the debug message shown, the Part was already register, or at least built when I'm trying to make some MaterialParts, and the array do have that Part object but it seemed that ContentTweaker refused to use it...
Log and Scripts:
[crafttweaker.log](https://github.com/The-Acronym-Coders/ContentTweaker/files/3638338/crafttweaker.log)

Components.zs : https://pastebin.com/SA49HyAA

**Comment by kindlich** [comment]
First of all, part names are usually snake-cased afaik
So try to change your part names first (e.g. `basic_gear`)

If that does not work, try changing from `material.registerPart(...)` to `part.registerToMaterials(...)`

**Comment by kindlich** [comment]
Oh, also, please don't just put your Crafttweaker.log file in there, upload it to pastebin or another service as well ^^

**Comment by Prunoideae** [comment]
Sorry for the late reply, my lab called my to finish off something.
After changing the part names to their lowercase form, the problems are gone, ty
