### ISSUE TITLE
Adding recipes to tinkers not adding in game despite no errors shown with command

### ISSUE THREAD

**Issue by keeper317** [The-Acronym-Coders/ContentTweaker#191]
I am unsure what you need to debug this so let me know and I will post them
[tinkers.zs.txt](https://github.com/The-Acronym-Coders/ContentTweaker/files/3665575/tinkers.zs.txt)
[tinkers_recipes.zs.txt](https://github.com/The-Acronym-Coders/ContentTweaker/files/3665583/tinkers_recipes.zs.txt)

**Comment by SkySom** [comment]
Are they .txt files on your computer?

**Comment by keeper317** [comment]
No they aren't txt files on my system, that was just the fastest way to upload them here.

**Comment by keeper317** [comment]
> Are they .txt files on your computer?

No, they aren't text files, I'm not an idiot. Why did you close this, the issue still stands?

**Comment by SkySom** [comment]
Well you uploaded txt files. And didn't provide logs so I'm gonna assume use error. And also Contenttweaker isn't responsible for recipes

**Comment by keeper317** [comment]
> Well you uploaded txt files. And didn't provide logs so I'm gonna assume use error. And also Contenttweaker isn't responsible for recipes

I specified I didn't know what else you needed, and how dumb would you have to be to not be using the correct file type, in fact that was the FIRST thing I checked for.

Meant to have this in craft tweaker, opened the issue on the wrong mod

**Comment by SkySom** [comment]
Modtweaker is what does Tinkers recipes. And I'm guessing your log shows nothing as that init method is not being called. I'm gonna guess you just pulled that from some pack, if you don't even know what mod properly adds Tinkers compat.
