### ISSUE TITLE
Problem with Script. Probebly bug?

### ISSUE THREAD

**Issue by drago87** [The-Acronym-Coders/ContentTweaker#198]
I'm trying to add some items and the first 2 script works (Crystal and Shard) but the last 2 dont work
[Items-Crysal.zs](https://pastebin.com/LhH3Khkj)

[Items-Shard.zs](https://pastebin.com/ZerBUnMz)

Gives a "could not find Vanillafactory" error
[Items-Clump.zs](https://pastebin.com/ityLmQYD)

Gives a "No such static member in mods.contenttweaker.VanillaFactory: createitem" error
[Items-DirtyDust](https://pastebin.com/Z0W1A0v6)

Each file is a Copy paste where i have changes the variable name and the string that i send

[crafttweaker.log](https://pastebin.com/vtqyjrhx)

Minecraft: 1.12.2
Forge: 14.23.5.2847
CraftTweaker2: 1.12-4.1.20
ContentTweaker: 1.12.2-4.9.1

**Comment by kindlich** [comment]
First:
it's create**I**tem (with a capital I)

Second: 
Why not use the materialSystem for that?

**Comment by drago87** [comment]
Totaly missed the capital I and capital F on some of the VanillaFactory

Did not know of the materialSystem Going to take a look at that
