### ISSUE TITLE
Question: How to begin a script for adding an item?

### ISSUE THREAD

**Issue by sipes42** [The-Acronym-Coders/ContentTweaker#2]
I have this bit of code based on a bit that I saw elsewhere:

> //Items
mods.content.Item.registerItem("Inferior Carrot", "inferiorCarrot", "inferiorCarrot", "misc", 50, 1, "sword", 2, true, []);

The main issue is that I know there is supposed to be something at the top similiar to this:

> import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Block;

But I don't know what should be there for adding an item rather than a block... Also, I can't even tell if what I've done so far is correct, and the logs give ZERO info about it, other than it started to load the file.

Any help you can offer would be greatly appreciated

**Comment by SkySom** [comment]
The first bit of code is 1.7.10 code. That won't work at all.

**Comment by sipes42** [comment]
Ah. Alright, that would explain much... I can't seem to find documentation anywhere, do you happen to have any links?

**Comment by sipes42** [comment]
found it I think, actually

**Comment by SkySom** [comment]
https://github.com/The-Acronym-Coders/ContentTweaker/wiki
