### ISSUE TITLE
harvestLevel data value

### ISSUE THREAD

**Issue by Magi1053** [The-Acronym-Coders/ContentTweaker#20]
Looking at Iron Ore it says i need Pickaxe (Iron) to mine it. I look at a custom ore and it says I need 3, but can be used with any pickaxe.
```
oreData.addDataValue("harvestTool", "pickaxe");
oreData.addDataValue("harvestLevel", "3");
```

**Comment by SkySom** [comment]
Fixed by all the data fixes done to properly support drops

**Comment by Magi1053** [comment]
Documentation link for the data value names?

**Comment by SkySom** [comment]
https://github.com/The-Acronym-Coders/ContentTweaker/wiki/Materials-V2-Test is the closest with all datavalues (Only ores, blocks, and fluids have them currently), the only one missing is "drops" as well as the fluid ones (I'm working on a PR to the craftTweaker documentation that lists all parttypes, parts, and datavalues
