### ISSUE TITLE
[Feature Request] Create blocks from templates

### ISSUE THREAD

**Issue by supersaiyansubtlety** [The-Acronym-Coders/ContentTweaker#200]
I think it would incredibly useful to allow the creation of blocks from a few templates like "trap_door",  "iron_trap_door", "door", "iron_door", "barrel" (like 1.14 barrels, just simpler chests), and block variants like "stair", "slab", and "wall". 
These would all have their vanilla-counterpart's models and behavior by default. Models could be overridden, with trap-doors and doors accepting two models that are swapped between. 
The barrel would also have an override to change it's inventory size to any n*m. 

Notes:
I understand doors might be considerably more complicated both for Team Acronym and users of CoT. Perhaps the template function for doors would take two `unlocalizedName`s and register two blocks, one for top and one for bottom. 
It might also be useful to have an additional template "toggle_block" that's basically a simpler trap door; a block with no directionality but one that toggles between two models on right-click.

**Comment by SkySom** [comment]
This is unlikely to happen. The material system was setup to do some of those, but Contenttweaker is mostly setup to just be simple item and block creation. Not copying everything else to change two properties.

**Comment by supersaiyansubtlety** [comment]
Fair enough
