### ISSUE TITLE
Script does not parse imports

### ISSUE THREAD

**Issue by AncientShotgun** [The-Acronym-Coders/ContentTweaker#202]
I am modifying my ZenScript files from the Omnifactory modpack to turn dust blocks (which were originally only defined as an item) into actual blocks.
Crafttweaker errors on line five and reports an invalid expression.

Relevant excerpt of Crafttweaker log: https://pastebin.com/G4LAp5Fr
Relevant excerpt from Script: https://pastebin.com/NmKmnStq
Modlist: https://pastebin.com/4VdnmV9M

As you can see, line 5 contains only an import, which should usually work. I have the correct loader for the script.

**Comment by SkySom** [comment]
I'm guessing there's a weird character or space in there. Not a Contenttweaker issue. Also you should always include full script.

**Comment by AncientShotgun** [comment]
Addendum: The error has appeared again, this time in a different script I have not touched ever since it was downloaded.

Once again, the error occurs only on the line that declares the import, in this case line 3.

New crafttweaker.log, this time complete: https://pastebin.com/N3kLFvbE
The new script itself, also in complete form, copied directly from the file into pastebin with no edits wahtsoever: https://pastebin.com/GkCULFrv
Modlist: has not changed, no updates. 

Since I have not modified this file for the duration of its lifespan, and it has worked the ~6 months up until now, meaning the original file author did not make any (fatal) mistakes in coding, I can only assume that it is a problem with ContentTweaker.

**Comment by SkySom** [comment]
That's not even a ContentTweaker script.

**Comment by AncientShotgun** [comment]
Ah, my apologies, I'll redirect it to the appropriate authorities.
What this tells me, however, is that this seems to be a problem with my version of Crafttweaker, not ContentTweaker. Mysteries upon mysteries!
