### ISSUE TITLE
Chicken Representation Lay Coefficient

### ISSUE THREAD

**Issue by MP3DSL** [The-Acronym-Coders/ContentTweaker#205]
I don't have a problem getting it all to work as I've made numerous working custom chickens. This question is more to clarify and know whether the **Lay Coefficient** can ever be **less than 0.1**.

It is documented that it is a float, and as such should be able to be be a smaller number. However, it doesn't specify what the smallest number possible can be, and after tweaking the chickens to be more balanced, I came across a scenario where I wanted the chicken's speed of production to be slower. When making the chicken's lay coefficient smaller than 0.1, the coefficient internally seemed to reset to a default of 1.

It's not a huge problem if it can't be any lower than 0.1. I just was curious if it could be and that maybe I was doing something wrong or am just crazy haha. But it would be nice to know the minimum limit and for it can be in the documentation as well.

If you have any suggestions about still slowing down the production, that feedback would be very welcomed as well. The only other option that comes to mind is just creating an intermediary step of crafting and have the chickens produce that instead.

Thanks

**Comment by SkySom** [comment]
Contenttweaker doesn't do anything to lay coefficient outside of pass it to the Chickens API. I don't know anything specific.

**Comment by MP3DSL** [comment]
Thanks for the swift reply @SkySom , I appreciate it.
It's not an issue, just something I noticed. That's good info to know tho as there may be a limiter in the API. If I had some more time today I would check it myself, but maybe another day this week
