### ISSUE TITLE
[1.12.2] Contenttweaker Script that works with Crafttweaker 4.1.20.564 does not with Crafttweaker 4.1.20.565

### ISSUE THREAD

**Issue by TeetoKaziim** [The-Acronym-Coders/ContentTweaker#206]
#### Issue Description:
Contenttweaker Script creating items errors and dies on 4.1.20.565 while working without a hitch on 4.1.20.564. In particular, the log seems to dislike the use of Commands.call in an itemRightClick function?

#### What happens:
Game launches, crafttweaker log full of errors, chat full of errors. First 2 blocks in the script successfully registered, nothing after that is registered.

#### What you expected to happen:
My very, _very_, good and **not embarrassing at all** (>.>) script from 2018 to keep working forever, a pillar of constancy in this sea of entropy we call life.  (<.<)

#### Script used:
https://gist.github.com/TeetoKaziim/86e442941ebd5e2fbaeadf73ef6a4378#file-custom_items-zs

#### crafttweaker.log files:
With 4.1.20.564: https://gist.github.com/TeetoKaziim/86e442941ebd5e2fbaeadf73ef6a4378#file-functioning_crafttweaker-log

With 4.1.20.565: https://gist.github.com/TeetoKaziim/86e442941ebd5e2fbaeadf73ef6a4378#file-non_functioning_crafttweaker-log

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Crafttweaker: 4.1.20.565
- Contenttweaker: 4.9.1
- Using a server: Happened Both On A Dedicated Server And On Client Alone.
- If yes, does the client have the exact same scripts? -- Yes.

#### Your most recent log file where the issue was present: 
`debug.log` : https://gist.github.com/TeetoKaziim/86e442941ebd5e2fbaeadf73ef6a4378#file-debug-log
`latest.log` : https://gist.github.com/TeetoKaziim/86e442941ebd5e2fbaeadf73ef6a4378#file-latest-log

**Comment by kindlich** [comment]
ZenScript issue, not related to ContentTweaker.
Also, this is being worked on ^^

**Comment by kindlich** [comment]
Closing this because the other issue was closed as well.
If this was not fixed, please answer and I'll reopen
