### ISSUE TITLE
Going Backwards On ContentTweaker Block causing player to sink.

### ISSUE THREAD

**Issue by TheMCSpacePro** [The-Acronym-Coders/ContentTweaker#207]
https://youtu.be/QRgX8G2Mg40
What the title says.

**Comment by SkySom** [comment]
Didn't post script, so I'm left with the only thought being an error with the script (Gonna guess slipperiness set to 0)

**Comment by TheMCSpacePro** [comment]
#loader contenttweaker

import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Block;

var copperOreBlock = VanillaFactory.createBlock("copper_ore", <blockmaterial:rock>);
copperOreBlock.setBlockHardness(5.0);
copperOreBlock.setBlockResistance(5.0);
copperOreBlock.setToolClass("pickaxe");
copperOreBlock.setToolLevel(1);
copperOreBlock.setBlockSoundType(<soundtype:stone>);
copperOreBlock.register();

I don't even HAVE that in my script. Well, the wiki never said anything about it, I think, so I had no idea that setting slipperiness to 0 caused that. What do I set it to in order to disable it? (Since this is closed, you might as well send it to 'seanrileymims@gmail.com')

**Comment by SkySom** [comment]
No it's called reopening the issue now you provided info, but that's not your exact script. as that isn't valid.

**Comment by TheMCSpacePro** [comment]
That is my script. It does allow the block to appear ingame.

https://imgur.com/a/LeIibAw

**Comment by TheMCSpacePro** [comment]
Ok, based on what was said eariler, it was an error on my part. I didn't define slipperiness, so I have set that to 1. Going to use trail and error now. https://imgur.com/a/FRHOlTC  Closing this.
