### ISSUE TITLE
Issues creating custom enchant effect

### ISSUE THREAD

**Issue by notWaterGuy12** [The-Acronym-Coders/ContentTweaker#208]
I'm having trouble finding documentation on how I can make an enchantment run a command on an attacked entity. This script is as far as I have been able to get to no success. The goal of the script is to make it run /kill on whatever entity the enchanted item hits.

https://pastebin.com/NsTLwJkd

Versions used:
CraftTweaker2-1.12-4.1.20.574.jar
ContentTweaker-1.12.2-4.9.1.jar

Any help is greatly appreciated

**Comment by SkySom** [comment]
The issue tracker is not for script assistance.that is what the discord is for.
