### ISSUE TITLE
Custom model for block does not load

### ISSUE THREAD

**Issue by notWaterGuy12** [The-Acronym-Coders/ContentTweaker#209]
I created a custom model for a block using Blockbench and it does not load the model for the block. I put the model onto a different block using resourceloader (not made with contenttweaker) and the model loaded completely fine. Is there something I need to do (possibly with blockstates) to get it to at least load the model? It recognizes the texture just fine, haven't been able to find anything on the problem.

**Comment by SkySom** [comment]
Check your logs, you likely haven't named something properly.

**Comment by notWaterGuy12** [comment]
Name is fine, went through the logs and couldn't find anything referencing the model
