### ISSUE TITLE
[1.15.2] Crash with NetherEx

### ISSUE THREAD

**Issue by StellaBiscuit** [The-Acronym-Coders/ContentTweaker#211]
ContentTweaker and NetherEx Together crashes the game

**Comment by StellaBiscuit** [comment]
will do the info

**Comment by StellaBiscuit** [comment]
wait a sec

**Comment by kindlich** [comment]
We'll need crash log, game log and if you had a script already then that and the crafttweaker log as well.
Additionally forge info and CrT and CoT version.

Does it crash _without_ netherex as well?

**Comment by StellaBiscuit** [comment]
First, it doesn't crashes without NetherEx, BUT it does a Fatal Error so it's the same problem
Second,
Forge Version : 31.2.33
CraftTweaker : 6.0.0.24
ContentTweaker : 1.0.0.develop17




NetherEx Crash VVV
Log:
[latest.log](https://github.com/CraftTweaker/ContentTweaker/files/4995884/latest.log)
Crash Report:
[crash-2020-07-29_11.47.22-client.txt](https://github.com/CraftTweaker/ContentTweaker/files/4995886/crash-2020-07-29_11.47.22-client.txt)
Script:
No Script
CraftTweaker Log:
[crafttweaker.log](https://github.com/CraftTweaker/ContentTweaker/files/4995899/crafttweaker.log)


ContentTweaker alone Fatal Error VVV
Log:
[latest.log](https://github.com/CraftTweaker/ContentTweaker/files/4995926/latest.log)
Crash Report:
None (Fatal Error)
Script:
No Script
CraftTweaker Log:
[crafttweaker.log](https://github.com/CraftTweaker/ContentTweaker/files/4995934/crafttweaker.log)

**Comment by StellaBiscuit** [comment]
Ok, newest version of CraftTweaker seems to correct the crash (WHY Twitch doesn't download latest, I will never know)
