### ISSUE TITLE
[1.15.2] Fatal Error?

### ISSUE THREAD

**Issue by Yourname942** [The-Acronym-Coders/ContentTweaker#214]
Does anyone know how to fix this crashing issue? 
I get a java.lang.NullPointerException after I launch Minecraft (during the Forge bootup/loading)
For some reason ContentTweaker is causing this error to occur:
java.lang.NullPointerException at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97)

First Crash: Bonsai Trees 2 Enabled: (failed with Bonsai Trees 2)
Latest Log: https://gist.github.com/Yourname942/c221044542cea6cebe8cda9434b8435b
Crash Log: https://gist.github.com/Yourname942/d3bc45fa46c3a331352f9e34f2524375

Second Crash: Bonsai Trees 2 Disabled: (now failed with Flux Networks)
Latest Log: https://gist.github.com/Yourname942/8d24e3f35fb3dbc0368b07c7ca45dc2f
Crash Log: https://gist.github.com/Yourname942/eede40d60fc91adece68ecabf0c6cfd5

Minecraft: 1.15.2
Forge: 31.2.36

Steps taken:
    Launch Twitch App
    Click Play (purple button in Twitch App)
    Click Play (green button in Minecraft Launcher)
    Crash occurs while Forge is loading mods 

Unfortunate Solution:
uninstall/remove ContentTweaker from my modpack

Thank you.

**Comment by dshadowwolf** [comment]
This appears to be a slight version bug with CraftTweaker. The latest "release" flagged version on CurseForge has this issue easily reproduced but with the August 1 released version (6.0.0.38) the issue goes away. It appears that there were massive changes in the CraftTweaker API provided logging facilities that have resolved this issue and that it is not, actually, a bug in ContentTweaker.

**Comment by kindlich** [comment]
AS dshadowwolf pointed out you need the latest version of CraftTweaker.
I also set it as a requirement for the next build of ContentTweaker so it will error earlier due to an outdated version of CraftTweaker.
