### ISSUE TITLE
[1.15.2] Loottables

### ISSUE THREAD

**Issue by TheUntamed** [The-Acronym-Coders/ContentTweaker#215]
Hi,

I have a coding question, maybe you can help me:
I'm trying to define block drops without creating a json file inside the data folder.
ContentTweaker allows to add blocks and those blocks have no loot table json.
I tried to figure out how you did that but I can't quite get thru your code.

**Comment by SkySom** [comment]
Install `The Loader` or `OpenLoader` and ContentTweaker will generate those files.
