### ISSUE TITLE
1.12 Block renders correctly in world, but has no texture in inventory

### ISSUE THREAD

**Issue by FrogBirddd** [The-Acronym-Coders/ContentTweaker#218]
![2020-10-20_20 47 38](https://user-images.githubusercontent.com/47725078/96659775-d7c22d00-1315-11eb-936c-f5521780b769.png)
The block I made renders perfectly when placed, but while in the inventory or dropped as an item it has no texture/model. I have already made several similar blocks using the same method which work fine, it's just this one. Script is below, if that helps.

#loader contenttweaker

import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Block;
import mods.contenttweaker.AxisAlignedBB;

var basin = VanillaFactory.createBlock("unfired_basin", <blockmaterial:clay>);
    basin.setAxisAlignedBB(AxisAlignedBB.create(0.0625d, 0.0d, 0.0625d, 0.9375d, 0.25d, 0.9375d));
    basin.setBlockSoundType(<soundtype:Ground>);
    basin.setFullBlock(false);
    basin.setBlockHardness(2.0);
    basin.setLightOpacity(0);
    basin.register();

var pot = VanillaFactory.createBlock("unfired_pot", <blockmaterial:clay>);
    pot.setAxisAlignedBB(AxisAlignedBB.create(0.125d, 0.0d, 0.125d, 0.875d, 0.8125, 0.875d));
    pot.setBlockSoundType(<soundtype:Ground>);
    pot.setFullBlock(false);
    pot.setBlockHardness(2.0);
    pot.setLightOpacity(0);
    pot.register();

var crucible = VanillaFactory.createBlock("unfired_crucible", <blockmaterial:clay>);
    crucible.setAxisAlignedBB(AxisAlignedBB.create(0.0625d, 0.0d, 0.0625d, 0.9375d, 0.9375d, 0.9375d));
    crucible.setBlockSoundType(<soundtype:Ground>);
    crucible.setFullBlock(false);
    crucible.setBlockHardness(2.0);
    crucible.setLightOpacity(0);
    crucible.register();

**Comment by SkySom** [comment]
That'd be a model issue, not a contenttweaker one.

**Comment by FrogBirddd** [comment]
Good to know, thank you for the quick reply and have a good day:)
