### ISSUE TITLE
Ability to add gasses, slurries, etc for Mekanism [Feature request]

### ISSUE THREAD

**Issue by Profilename1** [The-Acronym-Coders/ContentTweaker#219]
Mekanism is out on 1.16 now and with it being a pretty major mod, I would be greatly appreciated if you guys added support for adding some of the chemicals types used by the machines in that mod.

**Comment by kindlich** [comment]
This is currently in work by @pupnewfster to be added to Mekanism Directly.
Therefore I'm closing this one.

**Comment by pupnewfster** [comment]
Not being added until Mekanism V10.1, the specific issue about this is being tracked here: https://github.com/mekanism/Mekanism-Feature-Requests/issues/21
