### ISSUE TITLE
Request: Set Texture in ZS.

### ISSUE THREAD

**Issue by Magi1053** [The-Acronym-Coders/ContentTweaker#22]
For the purpose of looping though metals, set the texture dynamically with the metal name using string concatenation.
`part.setTexture("contenttweaker:block/ore_"~metal_name);`

**Comment by SkySom** [comment]
Removing this from current milestone, need to rethink how this works for Material Parts where there are more than one texture (Like Ores themselves, they have ore and ore shadow and particles. Gonna take a bit more thought than expected
