### ISSUE TITLE
Suggestion: Add a function to give blocks bookshelf functionality for the Enchanting Table

### ISSUE THREAD

**Issue by FrogBirddd** [The-Acronym-Coders/ContentTweaker#220]
For my personal pack I've added custom bookshelves for different wood types, which is perfect for just decoration but has no impact on the enchanting table. Basically I'm asking for something like "block.setEnchantPower(#);" where # is the strength of the block in relation to a vanilla bookshelf (0.5 would be half as strong, while 15 would max it out with one block, as examples).

**Comment by kindlich** [comment]
What version are you requesting this for?

**Comment by FrogBirddd** [comment]
> What version are you requesting this for?

In the case of the pack specifically I was in 1.12, but if that's not receiving updates it would still be nice to have it in more up to date versions.

**Comment by SkySom** [comment]
It already exists in 1.12.

**Comment by FrogBirddd** [comment]
> It already exists in 1.12.

My bad, I must have missed it. can you link the documentation?
