### ISSUE TITLE
Transparent blocks do not work

### ISSUE THREAD

**Issue by ghost** [The-Acronym-Coders/ContentTweaker#223]
I am using the latest version of CraftTweaker and ContentTweaker for 1.15.2.
I was trying to add a new plant block but could not get the transparency to display. The people in the Discord told me to set the material to a transparent one (in my case "plants") but it did not appear to change anything. The material clearly changed as the block color on maps changed and the block broke when pushed by a piston.
The same issues are present when I changed the parent model from "block/cube_all" to "block/cross", however in all screenshots it's set to "block/cube_all".

The block seems to render correctly in inventory no matter what the block material is set to:
![Screenshot of block in inventory](https://user-images.githubusercontent.com/11356733/102947740-01bcda80-4492-11eb-9bf0-f9c16d3e8c8b.png)

Transparency without Optifine installed:
![Transparency without Optifine installed](https://user-images.githubusercontent.com/11356733/102947807-2d3fc500-4492-11eb-9774-3146a96c0b06.png)

Transparency with Optifine installed (the only 1.15.2 Optifine version available is a preview):
![Transparency with Optifine installed](https://user-images.githubusercontent.com/11356733/102947781-1c8f4f00-4492-11eb-94d8-2634628fef7b.png)

The texture I used:
![rose](https://user-images.githubusercontent.com/11356733/102948820-c5d74480-4494-11eb-86cf-1009e219f476.png)

I tested all this with no mods other than Crafttweaker, Contenttweaker and in one of the screenshots, Optifine.

**Comment by jaredlll08** [comment]
I'm unable to reproduce.
![image](https://user-images.githubusercontent.com/5553605/134751098-f23340fb-2d68-48bf-9e57-ce447b797b8c.png)

I'm using the following script:
```zenscript
#loader contenttweaker
import mods.contenttweaker.block.BlockBuilder;
import mods.contenttweaker.block.BlockRenderType;
import mods.contenttweaker.block.advance.BlockBuilderAdvanced;

new BlockBuilder(<blockmaterial:glass>)
    .notSolid()
    .withHardnessAndResistance(0.3f)
    .withRenderType(BlockRenderType.TRANSLUCENT)
    .withType<BlockBuilderAdvanced>()
    .build("white_cloud");
```

Since we don't have your script, my only guess is that you weren't setting the BlockRenderType to `TRANSLUCENT`.
