### ISSUE TITLE
Not working Yet?

### ISSUE THREAD

**Issue by sysyss** [The-Acronym-Coders/ContentTweaker#225]
I play 1.16.4

I add mod. CraftinTweaker and ContentTweaker. (and Other.)
and I'm check Crafting Zs file is working. 
but Add item with ItemBuilder() Script didin't working 

Actually ContwntTweaker didn't add config file.

Im use. 

CraftTweaker-1.16.5-7.1.0.103
ContentTweaker-1.16-1.0.0.develop.11

What's the problem

**Comment by democat3457** [comment]
send script and crafttweaker.log
and what other mods are you using
we're not mind readers, we can't tell you the problem without more information

**Comment by sysyss** [comment]
For Check, Only install Jei/craftTwek/contenttwek and REcheckit. 
and know What is Problem.
using more than one #loader contenttweaker .zs file. if one file has problem, than any file is unloading but din't display log.
i use 3 sclipt ("bloc.zs","item.zs","recipe.zs") and item use example script(1.16) but block use old scirpt. (var Vanilafactory.) 
so didnt any contenttweaks item.

One problem is , check it way is only use command(/ct syntax) and it din't work with mineclaft command(/reload)

**Comment by democat3457** [comment]
sooooooo we still don't have scripts. if you have multiple, send them all over. and you say it doesn't display log, but we still don't have the log. if there is no log, then pull the latest.log or debug.log.

you aren't providing anything useful for us to help you

**Comment by sysyss** [comment]
sorry . that was my problem. not mod problem so i close it.
