### ISSUE TITLE
(sugestion) "withHarvestLevel" dosen't delete the drop when you mine it with the incorrect tool/ hands

### ISSUE THREAD

**Issue by Appdato** [The-Acronym-Coders/ContentTweaker#228]
My suggestion is that the "withHarvestLevel" can also delete the drop in use with a specific tool o your hands.
Another idea is making a new method just to allow this behaviour

**Comment by jaredlll08** [comment]
Not fully sure what you are asking, but there is `setRequiresTool`, which will make it that if you break the block with anything besides the harvest tool nothing drops.
