### ISSUE TITLE
Methods for giving items "enchanted" effect

### ISSUE THREAD

**Issue by OrdinatorStouff** [The-Acronym-Coders/ContentTweaker#23]
I would please like to be able to have a custom CoT-added item to "glow" with the vanilla enchant *effect*. I don't want them to be actually enchanted with anything, just take that appearance (i.e. actually additions "empowered" items are like this).

Perhaps could be done with a special RARITY enumerator if not it's own separate property?

**Comment by SkySom** [comment]
Sure. Easy enough.
