### ISSUE TITLE
Mod not tagged for 1.16.5 on CurseForge

### ISSUE THREAD

**Issue by Renari** [The-Acronym-Coders/ContentTweaker#230]
Please tag this mod as 1.16.5 compatible so that it can be more easily installed via launchers.

**Comment by democat3457** [comment]
but is it actually 1.16.5 compatible

**Comment by Renari** [comment]
I can confirm it works to the extent of not crashing on startup, past that I'm not sure.

**Comment by pm065** [comment]
It works absolutely fine in 1.16.5, but it isn't tagged as such

**Comment by SkySom** [comment]
Should be done
