### ISSUE TITLE
Not accepting variables

### ISSUE THREAD

**Issue by idkimanerd** [The-Acronym-Coders/ContentTweaker#239]
![image](https://user-images.githubusercontent.com/81585709/119083347-a77a6400-b9b4-11eb-8a1e-d8f81d5c6221.png)
![image](https://user-images.githubusercontent.com/81585709/119083367-b3febc80-b9b4-11eb-85b2-4454e8efe4f0.png)

When I load the modpack up, it says that lines 189-190(the last two) are not valid variables. how come?
heres mod list btw https://pastebin.com/vb98VvTg

**Comment by democat3457** [comment]
`creativeDank*n*ullPanel` lowercase n should be capitalized N

and the assignment should be lowercase C

the variables are case-sensitive, if you havent noticed
