### ISSUE TITLE
1.16 is interpreting color integers oddly

### ISSUE THREAD

**Issue by dshadowwolf** [The-Acronym-Coders/ContentTweaker#243]
It appears that any Builder taking a `color` parameter, if handed, say `0xcc88cc` interprets this, not as just RGB, but as if it was given as ARGB as `0x00cc88cc`. That is, it interprets a given 24bit RGB color - intended to have no alpha channel - as if it is a color with full transparency when it should see it as `0xffcc88cc`.

**Comment by kindlich** [comment]
@friendlyhj since #240 is merged, is this fixed?

**Comment by friendlyhj** [comment]
Fixed. Although I wonder why build failed.

**Comment by kindlich** [comment]
Build fixed, so I'll close this then
<https://www.curseforge.com/minecraft/mc-mods/contenttweaker/files/3383429>
