### ISSUE TITLE
I found a spelling mistake on the wiki

### ISSUE THREAD

**Issue by xianyujunshigeCDD** [The-Acronym-Coders/ContentTweaker#247]
Please forgive me for my poor English, so I use Google translation.

In the chapter "simple walkthrough", in the Chinese mode of items and blocks, the content Walker becomes the content reader. I hope you can correct this error.
https://docs.blamejared.com/1.16/zh/mods/contenttweaker/SimpleWalkthrough/

I was really tortured for a long time without noticing it. T-T

**Comment by jaredlll08** [comment]
The translations are handled on Crowdin:
https://crowdin.com/project/crafttweaker-documentation

Unfortunately we don't have any Chinese speakers on the team, so it is up to the community to fix this.
