### ISSUE TITLE
[1.16.5] Fluid properties not being applied.

### ISSUE THREAD

**Issue by Drymouthman** [The-Acronym-Coders/ContentTweaker#252]
Hello, I'm having some trouble with fluids in 1.16.5. I'm trying to make a new fluid, and while I manage to build it and make it show in-game with a proper texture and whatnot, the properties I set for it seem to be totally absent. When I jump into it, its like walking through air. Also it spreads at the same base rate as water, and doesn't burn on contact whenever I set the temperature high enough. Entities dropped into it aren't dragged either.
Here is the script:
```
#loader contenttweaker

import mods.contenttweaker.fluid.FluidBuilder;

//Fish oil
new FluidBuilder(false, 0xC4A82D, <resource:contenttweaker:fluid/fishoil>, <resource:contenttweaker:fluid/fishoil_flow>)
	.density(3000)
	.temperature(360)
	.viscosity(3000)
	.build("fish_oil");
```
I followed the /CT examples, so it should be up-to-date, and also the log isn't showing anything weird. Is it a bug or am I doing something wrong?

**Comment by Skarneck** [comment]
Same problem for me.
The example script doesn't work either.

```
#loader contenttweaker

import mods.contenttweaker.item.ItemBuilder;
import mods.contenttweaker.item.tool.ItemBuilderTool;
import mods.contenttweaker.block.BlockBuilder;
import mods.contenttweaker.block.stairs.BlockBuilderStairs;
import mods.contenttweaker.block.basic.BlockBuilderBasic;
import mods.contenttweaker.block.pillar.BlockBuilderPillarRotatable;
import mods.contenttweaker.fluid.FluidBuilder;

	#Ore

new BlockBuilder(<blockmaterial:rock>)
    .setRequiresTool()
    .withHardnessAndResistance(1.8f)
    .withHarvestLevel(2)
    .withHarvestTool(<tooltype:pickaxe>)
    .build("darkgem_ore");
	
    #Fluid

new FluidBuilder(true, 0xfff7d840)
    .density(3000)
    .temperature(4000)
    .viscosity(4000)
    .build("molten_cheese");
```

**Comment by SkySom** [comment]
Most that just sounds like how Fluids work nowadays. You gotta tag it was minecraft:water or minecraft:lava to get properties. Most those values have little effect on the inworld blocks
