### ISSUE TITLE
[1.12.2] Couldn't use the function 'itemInteractionForEntity' 

### ISSUE THREAD

**Issue by Dark2932** [The-Acronym-Coders/ContentTweaker#254]
I couldn't use the function 'itemInteractionForEntity' when creating a Item.
It told me "No such member in mods.contenttweaker.Item: itemInteractionForEntity"

ContentTweaker version: 4.10.0

**Comment by jaredlll08** [comment]
full script and log on pastebin please

**Comment by Dark2932** [comment]
script 1：https://paste.ubuntu.com/p/8KJVnzQCKB/
script 2：https://paste.ubuntu.com/p/9XGyg9BBcb/
logs：https://paste.ubuntu.com/p/dRp87Pbp4s/
Error is on the line 169 and 170.

**Comment by jaredlll08** [comment]
I have no idea what you are doing, but it isn't using ContentTweaker, it is using ZenUtils, so that is why you don't have access to that field.

**Comment by Dark2932** [comment]
OK，thanks.
