### ISSUE TITLE
Creating items

### ISSUE THREAD

**Issue by Zer0Lyfe** [The-Acronym-Coders/ContentTweaker#26]
I was trying to create an item to use and It didn't allow me to Import: 
import mods.contenttweaker.Item;

then comes up with this error:
Vanilla\CustomItem.zs:9 > No such member: Item
Vanilla\CustomItem.zs:9 > Not a valid type

[https://pastebin.com/LPW3ydz2](url)

**Comment by SkySom** [comment]
Fixed in Dev builds, should have a curse release this weekend
