### ISSUE TITLE
[1.18.2 - Forge] Crashes on startup

### ISSUE THREAD

**Issue by Shadowdragon019** [The-Acronym-Coders/ContentTweaker#260]
Log - https://gist.github.com/Shadowdragon019/3ee198e9b1db3166b0512135271cd6f5

Mod List:
ContentTweaker
CraftTweaker

Forge version - 40.1.68

**Comment by brisingraerowing** [comment]
Ran into this as well. Same stack trace.

**Comment by 435THz** [comment]
Can confirm. I had more mods and was on 40.1.67 but still same stack trace

**Comment by jaredlll08** [comment]
We are aware of the issue, we are investigating a fix, unfortunately it is hard to reproduce the actual issue on my local machine

**Comment by Nevrai** [comment]
I’m having the same issue, although my crash report looks a little different. I get this error:
`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException`

Nevertheless, I attempted to run the game on a fresh install with nothing but ContentTweaker and CraftTweaker (and Forge), but the game won’t launch. I hope you figure the issue out, Jared! The world depends on you.

**Crash report:** https://pastebin.com/raw/CV3ENbKE
**latest.log:** https://pastebin.com/raw/Fr0ZSBBZ

**Versions**
* **Minecraft:** 1.18.2
* **ContentTweaker:** 1.0.0+7 (latest)
* **CraftTweaker:** 9.1.182 (latest)
* **Forge:** 40.1.68 (latest)

**Comment by Nevrai** [comment]
The game launches normally now, after updating to ContentTweaker 1.0.0+9!

**Comment by remplerus** [comment]
can confirm, now the game starts as it should

**Comment by jaredlll08** [comment]
Resolved
