### ISSUE TITLE
[1.18.2] Crash on creating custom items

### ISSUE THREAD

**Issue by remplerus** [The-Acronym-Coders/ContentTweaker#263]
I'm trying to create a custom item using following script:
[https://pastebin.com/iDwgrqMF](https://pastebin.com/iDwgrqMF)

Crash log: [https://mclo.gs/yd3Usmd](https://mclo.gs/yd3Usmd)

Version used:
Forge: 40.1.69
CraftTweaker: 9.1.185
ContentTweaker: 1.0.0+10

**Comment by TheSilkMiner** [comment]
Should be fixed in a703826f8b79f6fabb100ec4893063d76cf65865. According to my tests, it works properly in production and dev, let me know if that's not the case
