### ISSUE TITLE
Item Models not generating

### ISSUE THREAD

**Issue by Zer0Lyfe** [The-Acronym-Coders/ContentTweaker#27]
I'm trying to add a texture to an item and will accept the texture in any way and I'm using the vers. 34 Jenkins ContentTweaker file and blocks work but items do not.
My script:
[https://pastebin.com/SkdSRsUN](url) 
My item is in \resources\contenttweaker\textures\items
My Item Name:
![image](https://user-images.githubusercontent.com/28994351/31125086-ae04a920-a879-11e7-9237-1126011f82c8.png)

I forgot an in-game image:
![2017-10-03_20 36 43](https://user-images.githubusercontent.com/28994351/31125382-bdd62e4a-a87a-11e7-8427-9aedc74761b2.png)

**Comment by SkySom** [comment]
Also need your crafttweaker log and instance logs.

**Comment by Zer0Lyfe** [comment]
The instance Log: Sorry it's so large.
[latest.log](https://github.com/The-Acronym-Coders/ContentTweaker/files/1352622/latest.log)
Crafttweaker log:
[crafttweaker.log](https://github.com/The-Acronym-Coders/ContentTweaker/files/1352628/crafttweaker.log)

**Comment by SkySom** [comment]
Everything works as long by manually creating the item jsons in models/item. Need to fix the system such that it generates them like for blocks.
