### ISSUE TITLE
Name Items in the Language File

### ISSUE THREAD

**Issue by DJJBanx** [The-Acronym-Coders/ContentTweaker#28]
Current Version: ContentTweaker-1.12-4.1.0-Snapshot.42
Forge Version: 14.23.0.2497

Items aren't named correctly when specified in the lang file. The item is created, the texture works, however the name does not. The item names are identical to the ones in-game. Let it be noted that naming works perfectly for new blocks.

Script (named NewItems.zs):
> #loader contenttweaker
> import mods.contenttweaker.VanillaFactory;
> import mods.contenttweaker.Item;
> 
> var pS = VanillaFactory.createItem("puttystick");
> var pG = VanillaFactory.createItem("puttygear");
> 
> pS.register();
> pG.register();

Lines put into language file:
> item.contenttweaker.puttygear.name = Putty Gear
> item.contenttweaker.puttystick.name = Putty Stick

**Comment by SkySom** [comment]
Turns out Lang files can't have spaces after the name
```
item.contenttweaker.puttystick.name=Putty Gear
```
is what it should be. I have added code to correct this in existing lang files
