### ISSUE TITLE
Crash upon trying to create Molten Mithril

### ISSUE THREAD

**Issue by Tedyhere** [The-Acronym-Coders/ContentTweaker#29]
https://pastebin.com/T5CXgYBm

Using

base-1.12-3.4.0-SNAPSHOT.68
ContentTweaker 1.12-4.1.0-Snapshot 42

Looks like it doesn't like duplicated molten metals when another mod adds in it's own molten item

**Comment by SkySom** [comment]
Material System now warns when duplicates are added, so this shouldn't happen anymore
