### ISSUE TITLE
1.18.2 mod doesn't work in server

### ISSUE THREAD

**Issue by CreeperLol25** [The-Acronym-Coders/ContentTweaker#291]
![image](https://github.com/user-attachments/assets/4e789041-f86a-44ef-b94d-dd9ddba289cb)
I have the same version of the server, and don't work. I tried to reinstall the mod, and nothing

**Comment by jaredlll08** [comment]
Make sure you have the same scripts on both the client and the server, contenttweaker scripts cannot be synced to the client, that is the only known reason for this error to appear.

**Comment by jaredlll08** [comment]
Closing due to no reply.
