### ISSUE TITLE
MaterialPart Bracket Handler

### ISSUE THREAD

**Issue by kindlich** [The-Acronym-Coders/ContentTweaker#32]
1) https://github.com/The-Acronym-Coders/ContentTweaker/blob/41cfabff0b6592b498c8ae72f08e6859272122bf/src/main/java/com/teamacronymcoders/contenttweaker/modules/materials/MaterialPartBracketHandler.java#L54
Change the sublist to `tokens.sublist(2, 5)`

2) Also:
https://github.com/The-Acronym-Coders/BASE/blob/98432a9fe9936c040ac803082e04f5a287bc2742/src/main/java/com/teamacronymcoders/base/materialsystem/MaterialSystem.java#L94-L97
Change the `toUpperCase(Locale.US)` to `toLowerCase(Locale.US)`

Why?
1) As of now`<materialPart:platinum:gear>` becomes `"platinum:"` as sublist's upper boundary is exclusive
2) When you register the MaterialPart as `material:PART` you cannot find it in the map as you format your whole query to `material:part`

**Comment by SkySom** [comment]
Fixed in Dev. Will be in next release!
