### ISSUE TITLE
Conditionals

### ISSUE THREAD

**Issue by Divineaspect** [The-Acronym-Coders/ContentTweaker#4]
Dimensions, Biomes, Hot, Dry, Wet, Cold.
Is Raining, Is night, is Moonphase?

**Comment by SkySom** [comment]
https://github.com/The-Acronym-Coders/ContentTweaker/blob/develop/src/main/java/com/teamacronymcoders/contenttweaker/api/wrappers/biome/CTBiome.java and https://github.com/The-Acronym-Coders/ContentTweaker/blob/develop/src/main/java/com/teamacronymcoders/contenttweaker/api/wrappers/world/MCWorld.java should suit your fancy!
