### ISSUE TITLE
Problem with fluid textures

### ISSUE THREAD

**Issue by Frinn38** [The-Acronym-Coders/ContentTweaker#41]
Hello,
I've add a fluid with content tweaker, the fluid is registered and apprear in jei.
However when I take a bucket of this fluid it seems empty and, when placed on the ground the fluid have no texture.
![image](https://user-images.githubusercontent.com/32675710/31796761-59d7fbea-b52b-11e7-9d6b-a264bddd0a5b.png)
For the texture y use the default with an orange color.
I don't know if I done anything wrong in the fluid creation or if content tweaker is in conflict with another mod so I join my script and the logs.
My script : https://pastebin.com/RQYyUY48
The latest.log : https://pastebin.com/nW75gX7j

Thanks for your help.

**Comment by SkySom** [comment]
Yep its know. I mentioned it in the changelog

**Comment by Frinn38** [comment]
Ok so its normal and will be corrected in the 4.3.0 update.
thanks so much for the very fast answer and good luck for dev this mod.
