### ISSUE TITLE
Feature/MaterialSystem: Add command to log registered parts, materials, etc

### ISSUE THREAD

**Issue by kindlich** [The-Acronym-Coders/ContentTweaker#45]
### Description:
For debugging purposes it can be really helpful to have commands that prints all registered parts and materials and whatnot.

### What exactly do I want?

- Register a `/ct registered_materials` command
- Register a `/ct registered_parts` command
- Register a `/ct registered_materialParts` command
- Register a `/ct registered_partTypes` command

Thank you for reading this

**Comment by SkySom** [comment]
Simple enough
