### ISSUE TITLE
1.12.2 - Add/Change oredict for Dense Plates

### ISSUE THREAD

**Issue by KAfable** [The-Acronym-Coders/ContentTweaker#48]
Other mods with existing Dense Plates (most notably IC2) use ore dict entry of plateDenseXYZ, where CoT currently has it at densePlateXYZ. Could you add/change an ore dict entry to all dense plates that make it match IC2's?

**Comment by justinrusso** [comment]
So.. what do they do when its Dense Iron?

**Comment by SkySom** [comment]
plateDenseIron

**Comment by justinrusso** [comment]
Dense Iron Dense Plate*

**Comment by SkySom** [comment]
Fixed by https://github.com/The-Acronym-Coders/BASE/commit/772fd257ce2907b1ac4152db0717e839494e89a4
