### ISSUE TITLE
Add optional bool to Command.call to bypass printing command to chat

### ISSUE THREAD

**Issue by superfluke** [The-Acronym-Coders/ContentTweaker#53]
![image](https://user-images.githubusercontent.com/20022336/33456893-cdb961fa-d5ee-11e7-89bf-b15f4772743a.png)

**Comment by SkySom** [comment]
Added by: https://github.com/The-Acronym-Coders/ContentTweaker/commit/211fac561daa40c1a9ee6f8d9cd420caaa773895
