### ISSUE TITLE
Add "stickMaterial"to the OreDict of Material System Rods

### ISSUE THREAD

**Issue by KAfable** [The-Acronym-Coders/ContentTweaker#54]
stickAluminum and stickIron is the ore dictionary convention for rods of that specific metal (using IC2 and Immersive Engineering as an example). The only items that seem to use rodMaterial, which is what ContentTweaker currently follows, as an ore dictionary is Thermal Foundation for its retextured Blaze mobs (Blizz, Blitz, etc.). 

Tinker's uses 'partToolRod' for it's ore dictionary so I don't think it should be part of the equation.,

**Comment by SkySom** [comment]
I guess I could support all of them. Not that hard now.

**Comment by SkySom** [comment]
Fixed by https://github.com/The-Acronym-Coders/BASE/commit/772fd257ce2907b1ac4152db0717e839494e89a4
