### ISSUE TITLE
Crash when creating armor with properties

### ISSUE THREAD

**Issue by Pabilo8** [The-Acronym-Coders/ContentTweaker#57]
I tried to make armor with properties, but when I load the game it crashes at initialization.
Here's the crash log: https://pastebin.com/WAVmLUZr.
`#loader contenttweaker
    import mods.contenttweaker.MaterialSystem;
	import mods.contenttweaker.Material;
	import mods.contenttweaker.MaterialPartData;
	
    var void_steel = MaterialSystem.getMaterialBuilder().setName("Void Steel").setColor(1713235).build();
    var ore_types = ["ore", "poor_ore", "dense_ore"] as string[];
	var part_names = 
["ingot","double_ingot","nugget","plate","double_plate","gear","mechanical_component","dust","unpure_dust","screw","rod","bolt"] as string[];

	void_steel.registerParts(part_names);

        var blockData = void_steel.registerPart("block").getData();
        blockData.addDataValue("hardness", "5");
        blockData.addDataValue("resistance", "30");
        blockData.addDataValue("harvestTool", "pickaxe");
        blockData.addDataValue("harvestLevel", "4");
		
	var plateArmour = void_steel.registerPart("armor").getData();
        plateArmour.addDataValue("durability", "2048");
        plateArmour.addDataValue("enchantability", "1000");
        plateArmour.addDataValue("reduction", "24,32,28,24");
        plateArmour.addDataValue("toughness", "20.0");
		
		`

**Comment by SkySom** [comment]
Fixed in BASE 3.5.1 (Should be on Curse soon)
