### ISSUE TITLE
[1.10.2-2.1.0] Crash upon using example item script

### ISSUE THREAD

**Issue by sipes42** [The-Acronym-Coders/ContentTweaker#6]
The client crashes upon using the example item script from the wiki:

>import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Item;
import mods.contenttweaker.IItemRightClick;
import mods.contenttweaker.Commands;
>
>var zsItem = VanillaFactory.createItem("zs_item");
zsItem.maxStackSize = 8;
zsItem.rarity = "rare";
zsItem.creativeTab = zsCreativeTab;
zsItem.smeltingExperience = 10;
zsItem.toolClass = "pickaxe";
zsItem.toolLevel = 5;
zsItem.beaconPayment = true;
zsItem.itemRightClick = function(stack, world, player, hand) {
    Commands.call("scoreboard players set @p name 5", player, world);
    return "Pass";
};
zsItem.register();

[fml-client-latest.txt](https://github.com/The-Acronym-Coders/ContentTweaker/files/1048868/fml-client-latest.txt)

Should I be changing something in the script, or is this an issue with the mod?

**Comment by SkySom** [comment]
Update BASE to 1.4. Don't know why Dependencies didn't update to throw an error if you didn't have at least 1.4.

**Comment by sipes42** [comment]
I am not sure what you mean. I am not particularly experienced, and I got the most recent release from the Curse/Twitch launcher. What exactly should I be downloading and replacing?

**Comment by SkySom** [comment]
Newest version is 1.4.0. Should be on curse.

**Comment by sipes42** [comment]
I have the latest version listed installed... So either it is not properly listed on Curse, there is an issue with my curse client, or there is still an issue. It would seem that it is the right version, given that the release date listed is 5/30/2017.

![capture](https://cloud.githubusercontent.com/assets/21108418/26755954/da1c3d9e-484c-11e7-8b0c-43cc64106c20.PNG)

**Comment by Lanse505** [comment]
You're showing CoT 2.1.0.
What SkySom asked you to do is to update to BASE 1.4.0 which is the lib mod for CoT.
Have you got BASE 1.4.0 on the client or not?

**Comment by sipes42** [comment]
I do now, thank you. Just knowing that B.A.S.E is a separate mod and not part of the actual ContentTweaker mod helped a lot, although perhaps it should have been obvious.

**Comment by Lanse505** [comment]
Perhaps ;)

Have a good one and let us know if it still doesn't work properly :P <3

**Comment by sipes42** [comment]
No longer crashes, but this issue persists:
#3

**Comment by Lanse505** [comment]
Gonna be looking into it, I'll return once I have something new

**Comment by Lanse505** [comment]
@sipes42 
This Script works and we'll be updating the examples:
```
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Block;
import mods.contenttweaker.Item;
import mods.contenttweaker.IItemRightClick;
import mods.contenttweaker.Commands;

var zsCreativeTab = VanillaFactory.createCreativeTab("zsCreativeTab", <minecraft:stone>);

var zsBlock = VanillaFactory.createBlock("zs_block", <material:iron>);
zsBlock.creativeTab = zsCreativeTab;
zsBlock.fullBlock = true;
zsBlock.lightOpacity = 255;
zsBlock.translucent = true;
zsBlock.lightValue = 1.0;
zsBlock.blockHardness = 5.0;
zsBlock.blockResistance = 5.0;
zsBlock.toolClass = "pickaxe";
zsBlock.toolLevel = 2;
zsBlock.blockSoundType = <soundtype:metal>;
zsBlock.register();

var zsItem = VanillaFactory.createItem("zs_item");
zsItem.maxStackSize = 8;
zsItem.rarity = "rare";
zsItem.creativeTab = zsCreativeTab;
zsItem.smeltingExperience = 10;
zsItem.toolClass = "pickaxe";
zsItem.toolLevel = 5;
zsItem.beaconPayment = true;
zsItem.register();
```

That script contains both the code for an example item, block and creativeTab.
We'll be splitting it up for the example code later on

**Comment by Lanse505** [comment]
@sipes42 
Here they are seperated


Block:
```
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Block;
var zsCreativeTab = VanillaFactory.createCreativeTab("zsCreativeTab", <minecraft:stone>);
var zsBlock = VanillaFactory.createBlock("zs_block", <material:iron>);
zsBlock.creativeTab = zsCreativeTab;
zsBlock.fullBlock = true;
zsBlock.lightOpacity = 255;
zsBlock.translucent = true;
zsBlock.lightValue = 1.0;
zsBlock.blockHardness = 5.0;
zsBlock.blockResistance = 5.0;
zsBlock.toolClass = "pickaxe";
zsBlock.toolLevel = 2;
zsBlock.blockSoundType = <soundtype:metal>;
zsBlock.register();
```

Item:
```
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Item;
var zsCreativeTab = VanillaFactory.createCreativeTab("zsCreativeTab", <minecraft:stone>);
var zsItem = VanillaFactory.createItem("zs_item");
zsItem.maxStackSize = 8;
zsItem.rarity = "rare";
zsItem.creativeTab = zsCreativeTab;
zsItem.smeltingExperience = 10;
zsItem.toolClass = "pickaxe";
zsItem.toolLevel = 5;
zsItem.beaconPayment = true;
zsItem.register();
```
