### ISSUE TITLE
Example script not working

### ISSUE THREAD

**Issue by Thedrummonger** [The-Acronym-Coders/ContentTweaker#65]
Whenever I tried to create a custom item I was met with this error "Error executing {[0:crafttweaker]: CustomItems.zs}: ALL REGISTERING MUST HAPPEN BEFORE REGISTRY EVENT" I assumed I was doing something incorrect so I tried to use the example given on the crafttweaker wiki and was given the same error.
Script: https://pastebin.com/aYiNE5jy
CraftTweaker Log: https://pastebin.com/63dUhR1f
Forge Log: https://pastebin.com/QmzBkQj3
There are no other scripts in my instance and the only mod installed other than those required for content tweaker is JEI
Mod Versions:
base-1.12.2-3.5.0
ContentTweaker-1.12.2-4.3.0
CraftTweaker2-1.12-4.0.12
Forge-14.23.1.2589

**Comment by Lanse505** [comment]
Where did you grab the example from?

**Comment by Thedrummonger** [comment]
The crafttweaker Wiki under the walk through section in the ContentTweaker tab.
http://crafttweaker.readthedocs.io/en/latest/#Mods/ContentTweaker/WalkThrough/

Is should also note the example item script from this GitHubs wiki section also gave me the same error.
https://github.com/The-Acronym-Coders/ContentTweaker/wiki/Items
When I tried that one I removed the 
zsItem.creativeTab = zsCreativeTab;
Line since I had not made that creative tab.

**Comment by Lanse505** [comment]
You didn't include the 
```
#loader contenttweaker 
```
at the very top of the example script

The "#loader contenttweaker" **NEEDS** to be there for the script to load properly.

The Github wiki is WAY out of date and shouldn't be used.
I will be cleaning it up within the coming week hopefully is the plan.

**Comment by Thedrummonger** [comment]
Can't believe I missed that! Thanks for the assist!

**Comment by Lanse505** [comment]
No problems!
