### ISSUE TITLE
Will this work 

### ISSUE THREAD

**Issue by Adarcer** [The-Acronym-Coders/ContentTweaker#67]
I am a person who likes Extra utilities block compression feature, in a unpublished 1.7.10 pack using loot++ i created a bunch of compressed blocks too keep inventorys a little less cluttered along with minetweaker recipes that used the blocks. I am trying to repeat this in a 1.12.2 pack and due to not having too many examples I have a feeling that i maybe missing {} and , in between the created blocks or something (used to .json :P).. here is a example from the script i am trying to make as you can see i am even trying to even use meta data which i am not sure is supported.

[spoiler]

#loader contenttweaker
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.MaterialPart;
import mods.contenttweaker.MaterialSystem;
import mods.contenttweaker.Material;
import mods.contenttweaker.Item;
import mods.contenttweaker.Block;
import mods.contenttweaker.PartBuilder;

//Marble Blocks
var "Compressed Marble" = VanillaFactory.createBlock("compmarble", <blockmaterial:rock>);
comp_marble.fullBlock = true;
comp_marble.setLightOpacity(255);
comp_marble.setLightValue(0);
comp_marble.setBlockHardness(1.5);
comp_marble.setBlockResistance(30.0);
comp_marble.setToolClass("pickaxe");
comp_marble.setToolLevel(0);
comp_marble.setBlockSoundType(<soundtype:rock>);
comp_marble.setSlipperiness(0.6);
comp_marble.register();

var "Double Compressed Marble" = VanillaFactory.createBlock("compmarble:1", <blockmaterial:rock>);
comp_marble:1.fullBlock = true;
comp_marble:1.setLightOpacity(255);
comp_marble:1.setLightValue(0);
comp_marble:1.setBlockHardness(3.0);
comp_marble:1.setBlockResistance(40.0);
comp_marble:1.setToolClass("pickaxe");
comp_marble:1.setToolLevel(0);
comp_marble:1.setBlockSoundType(<soundtype:rock>);
comp_marble:1.setSlipperiness(0.6);
comp_marble:1.register();

[/spoiler]

**Comment by SkySom** [comment]
Well first off that script wouldn't compile :D

**Comment by Adarcer** [comment]
well glad i asked first what am i doing wrong ?

**Comment by SkySom** [comment]
https://discord.gg/9UJpqs I'm working on a version of that, that should work, but go on and pop in here and I can chat a little on where you're off a bit.
