### ISSUE TITLE
IItemDestroySpeed does not exist.

### ISSUE THREAD

**Issue by Zer0Lyfe** [The-Acronym-Coders/ContentTweaker#68]
So I was trying to create a tool and I was trying to edit the speed of the tool but when i /ct syntax it says it doesn't exist.

Gist for CT script:
https://gist.github.com/Zer0Lyfe/fe9176737edf9122fccb5e6b72d7ba8c
Gist for Log:
https://gist.github.com/Zer0Lyfe/d7051af8008ab7f6e1bd0aa2ee574959
Links to where i was getting the information to make the tool:
http://crafttweaker.readthedocs.io/en/latest/#Mods/ContentTweaker/Vanilla/Creatable_Content/Item/

http://crafttweaker.readthedocs.io/en/latest/#Mods/ContentTweaker/Vanilla/Advanced_Functionality/Functions/IItemDestroySpeed

**Comment by kindlich** [comment]
`itemDestroySpeed`, going to be changed in the wiki soon, in the meantime, use this wiki for CoT (but not the CrT part, that's not yet released...)
<http://crafttwaeker-docu.readthedocs.io/en/cot/#Mods/ContentTweaker/Vanilla/Creatable_Content/Item/>

**Comment by Zer0Lyfe** [comment]
OK thank you :D

**Comment by Zer0Lyfe** [comment]
so there is another error saying it cannot Cannot cast int to ZenTypeNative: mods.contenttweaker.IItemDestroySpeed

and i did change it to
flinthatchet.itemDestroySpeed = 5;

**Comment by kindlich** [comment]
IItemDestroySpeed is a function that returns a float:
```
item.itemDestroySpeed = function(item, blockstate) {
return 5.0 as float;
}
```

**Comment by Zer0Lyfe** [comment]
Cool. thanks for your help with this :D
