### ISSUE TITLE
Certain Material Parts not Localizing when generated:

### ISSUE THREAD

**Issue by TeetoKaziim** [The-Acronym-Coders/ContentTweaker#71]
Forge: 14.23.2.2611
Base: 3.6.0
Content Tweaker: 4.4.1
Craft Tweaker: 4.1.2

Other Mods:
JEI: 4.8.5.147
Hwyla: 1.8.23-B38

This script:
https://gist.github.com/TeetoKaziim/5d3f44a353818355d525e5eedef51b54

Successfully generates a full list of lead parts, but the following ones are showing "base.part.partname" instead of a localized name:
clump
dirty_dust
shard
I guess the list is shorter than I thought it would be.

**Comment by septemberWaves** [comment]
I have also experienced this issue. Attempting to use the localization file (in the same way it would be used when creating a new part) does not work to fix the localization of these parts, although it works for new part types.
