### ISSUE TITLE
Using "*" to define the number of outputs does not work with the <materialpart:material:part> brackethandler.

### ISSUE THREAD

**Issue by TeetoKaziim** [The-Acronym-Coders/ContentTweaker#86]
Mods Installed:
B.A.S.E 1.12.2-3.6.1
Contentweaker 1.12.2-4.4.1
Crafttweaker 1.12.4.1.4
Hwyla 1.8.23-B38_1.12
Just Enough Items 1.12.2-4.8.5.157

Using the following 2 scripts

The material and part script for contenttweaker: https://pastebin.com/raw/sZPwAayp
The crafting recipes: https://pastebin.com/raw/ck8aV2uN

Craft Tweaker log that generates when launching with these scripts:
https://pastebin.com/raw/dfchbbRW

What happens in game:
The following is sent to chat on worldload:
```
ERROR: crafting_recipes.zs:9 > operator not supported
ERROR: Null not allowed in shapeless recipes! Recipe for: null not created!
```
The "Ender Nugget" part shows up in game.
The recipe for "1 nugget crafted from 1 ender pearl" shows up in JEI, and can be crafted.
The recipe for "5 stone crafted from 2 enderpearls" shows up in JEI, and can be crafted.
The recipe for "9 nuggets crafted from 3 enderpearls" does not show up in JEI, and cannot be crafted.

https://i.imgur.com/oHcZzgZ.png

My theory: "*" is an operator, and appears to not be supported by the <materialpart:material:part> bracket handler when used in recipes, for, some reason?

**Comment by TeetoKaziim** [comment]
Update:

At kindlich's prompting, tested all 3 of:
```
<materialpart:ender:nugget>.withAmount(9)
<materialpart:ender:nugget>.getItemStack() * 9
<materialpart:ender:nugget>.getItemStack().withAmount(9)
```
All 3 worked fine. So there's at least a workaround.

**Comment by SkySom** [comment]
Fixed on CraftTweaker side
