### ISSUE TITLE
Error: [contenttweaker]: Error executing {[0:contenttweaker]:ContentTweaker.zs}: null

### ISSUE THREAD

**Issue by lobbienjonsji** [The-Acronym-Coders/ContentTweaker#90]
While I was using Contenttweaker i made an item with an IItemUse function and got this error message:
Error: [contenttweaker]: Error executing {[0:contenttweaker]:ContentTweaker.zs}: null
[ErroredScript.txt](https://github.com/The-Acronym-Coders/ContentTweaker/files/1756039/ErroredScript.txt)
What does this mean?

**Comment by justinrusso** [comment]
The stack trace below that line in the `creafttweaker.log` explains the error. Please include your `crafttweaker.log` file.

**Comment by lobbienjonsji** [comment]
java.lang.NegativeArraySizeException

probably is not working because of pos.getOffset("south", -1);
[crafttweaker.txt](https://github.com/The-Acronym-Coders/ContentTweaker/files/1756140/crafttweaker.txt)

**Comment by lobbienjonsji** [comment]
no that did not work

**Comment by lobbienjonsji** [comment]
found the error. Apparently zenscript does not like &&.
