### ISSUE TITLE
[4.5.0] No enum constant net.minecraft.util.EnumFacing.up

### ISSUE THREAD

**Issue by Rosethorns** [The-Acronym-Coders/ContentTweaker#93]
When using the following script
![image](https://user-images.githubusercontent.com/2171914/37252881-52307b00-258e-11e8-8262-b27ce371ad11.png)

Minecraft will crash with the error: No enum constant net.minecraft.util.EnumFacing.up

Pastebin: https://pastebin.com/U4eibe7b

**Comment by SkySom** [comment]
For now if you do "UP" instead of "up" it should work. Though I will make this less prone to error.
