### ISSUE TITLE
Removing consecutive IE metal press recipes- ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: Recipes\test.zs}: null

### ISSUE THREAD

**Issue by CelestialPhoenix** [The-Acronym-Coders/ContentTweaker#94]
When removing a set of consecutive items from the Immersive Engineering metal press, the last item from the set errors out and the remainder of the script does not load.
(the targeted press recipe shows as removed in JEI)
`mods.immersiveengineering.MetalPress.removeRecipe(<thermalfoundation:material:295>);`
produces the error.
extract from ContentTweaker log- https://pastebin.com/F2ESSFny
(full CT log is over 1400 lines long)

scripts for the other gear types are work perfectly fine. 
`mods.immersiveengineering.MetalPress.removeRecipe(<thermalfoundation:material:292>);
mods.immersiveengineering.MetalPress.removeRecipe(<thermalfoundation:material:293>);
mods.immersiveengineering.MetalPress.removeRecipe(<thermalfoundation:material:294>);`

Same thing occurs when removing recipes for the IE wire items; steel wire errors out;
`mods.immersiveengineering.MetalPress.removeRecipe(<immersiveengineering:material:23>);`
while the previous recipes work ok;
`mods.immersiveengineering.MetalPress.removeRecipe(<immersiveengineering:material:20>);
mods.immersiveengineering.MetalPress.removeRecipe(<immersiveengineering:material:21>);
mods.immersiveengineering.MetalPress.removeRecipe(<immersiveengineering:material:22>);`

**Comment by SkySom** [comment]
And is this a ContentTweaker issue how? Looks like it's all in IEs CraftTweaker handling which is in IE itself

**Comment by CelestialPhoenix** [comment]
My bad. Will post it in IE github
