### ISSUE TITLE
Material Parts Not Showing In JEI

### ISSUE THREAD

**Issue by septemberWaves** [The-Acronym-Coders/ContentTweaker#96]
I generated a large number of parts using the material system. They exist in game, but are only accessible from the B.A.S.E creative tab; they do not exist in JEI and cannot be found in the creative search tab. I am _sure_ I'm not the only person who's encountered this problem. The code clearly _works_, since the items do generate as expected (including custom textures and localization), but something is going wrong. Is there an easy and obvious fix for this, or will it depend on my code (I can provide a pastebin if needed)?

**Comment by SkySom** [comment]
There's a config option in JEI for number of subitems to show. Increase that and your items will show.

**Comment by septemberWaves** [comment]
Thanks for the assistance.
