### ISSUE TITLE
[Help Request] Not Bug, looking for texture help for Content Tweaker

### ISSUE THREAD

**Issue by BonaireDreams** [The-Acronym-Coders/ContentTweaker#99]
Not a bug, looking for community help. Tried searching all wikis and was unable to find answer.

Hi Folks, Looking for some help to update textures for ContentTweaker recipes. PLaying SevTech: Ages, which uses Content Tweaker for custom recipes. I have a good 75% of Sevtech looking pretty with Sphax but can not for the life of me find the location for contenttweakers textures. IE gears and plates (etc). have been added. All the wiki's for minetweaker/crafttweaker/contentweaker indicate that the pngs should be in resources/textures/items etc. But all I can find is .json files in the models which reference base:textures/items.

Looking for help on finding

location to put the new textures (do they go in resourcepacks/texturepack.zip under assets/contenttweaker/items /blocks etc , or do my updated textures go in resources/contenttweaker/textures/items /blocks

where can I find the correct filenames for the items, ie gear_copper.png, gearCopper.png or whetever it may be.

Thanks in advance

**Comment by SkySom** [comment]
The Material system stuff that Sevtech uses does automatically provide textures. You can change the jsons to point elsewhere.

**Comment by BonaireDreams** [comment]
Hey SkySom, I'm more of a textures guy and have just dabble slightly into contenttweaker to add a few recipes. So am not sure how to change where it points. For example, the resources/contenttweaker/models/item folder has a file called bronze_plate.json.
 Its contents are:
`{
  "parent": "item/generated",
  "textures": {
    "layer0": "base:items/plate"
  }
}`

What would I need to change to have that use a standard bronzeplate.png texture file located in Resourcepacks/texturepack.zip-> assets/contenttweaker/textures/items/bronzeplate.png

Or even individual .png files in the resources/contenttweaker/textures/items folder as described in the wiki.

Appreciate the help

**Comment by kindlich** [comment]
That depens on whether you want to change ALL plate textures or only the bronze one?

The material system itself renders the items using one central texture and then  coloring that one.

The `"layer0"` property states where the item's base texture is to be found. If you want to change the base texture, you would have to create a .png at`resources/base/items/plate.png`

If you want to chamge a single item's texture, you can change the layer0 property to a new path and create the texture accordingly.

**Comment by BonaireDreams** [comment]
Ok, that mostly makes sense. I should have specified I'd make textures for each item. So I'll create textures in the folder resources/contenttweaker/textures/items/plate_bronze.png and then the new code in the .json file would be

'{ "parent": "item/generated", "textures": { "resources/contenttweaker/textures/items/plate_bronze.png" } }'

Is that correct?

**Comment by kindlich** [comment]
You would need to keep layer0 iirc and your resource path property to look like 
`contenttweaker:items/plate_bronze.png`
For the path you stated above.

**Comment by BonaireDreams** [comment]
Hmmm didn't work. I'll play some more with it tomorrow after work but you've got me going in the right direction. I think I just need to figure out the correct formatting for the path.

Thanks!!

**Comment by SkySom** [comment]
Haven't heard anything back, gonna close.
